\documentclass[a4paper,11pt]{article}
\usepackage{listings}
\usepackage{indentfirst}
\usepackage{amsmath}
\usepackage{algorithm}
\usepackage{algorithmic}
\usepackage{graphicx}
\title{COMS 4761, Assignment 4}
\author{Jing He:jh3283}
\begin{document}
\maketitle
% \large\textbf{COMS 4761, Assignment 4} \\

% \textbf{Jing HE:jh3283 }
\textbf{1.Sol:}

To find the index of original position in genome is in fact a tracing back question. To start with storing a vector of \ref{RR} $=[1..3*10^{9}$], each number need 32 bits, and the total storage would be $S_{0} = 32 * 3*10^{9}$. To save space, we adopt the similar thrifty storage strategy: index every I rows, so the total bits stored in total would be $log(3*10^{9}/I) * S_{0} / I$, so $log(3*10^{9}/I) * 3*10^{9} \leq I*3*10^{9}$ \\

when the interval I > 27, the storage space would be less than $3 * 10^{9}$, the each searching, we can tracing the index. the expectation $\#$ of index one reads will hit is 32/28 = 8/7\\


pseudo code: 
\begin{verbatim}
	step 1 store:
				for ( 1:3*10^9) 
					if( i modular 28 == 0) 
					  store index into a vector S_{1} = {1...107142857}
	step 2 trace: 
					index_flag =0;
					n = length of reads;
					while (n!=0)    //trace from the end to the start
						{   
					   if( (read[n] have index) && (index_flag ==0) )
					   {  index_flag =1;
					      original_index = index_val - n; 
					   }

\end{verbatim}
\textbf{2.a.Sol:}

Heterozygote:
\begin{align}
 Pr(C) = Pr(A) &= (1-1\%)/2 + 0.5*\dfrac{1}{300} \\
 							  % &= \Sexpr{0.99/2 + 0.5 * 1/300 } \\
                &= 0.4966667 \\
 				Pr(T) = Pr(G) &= \dfrac{1}{2}\dfrac{1}{300} * 2 \\
 							  % &= \Sexpr{1/300} \\
                 &= 0.003333333 
 \end{align}
Homozygote: 

 \begin{align}
 &Pr(A) = (1- 1\%) \\
          &= 99\%  \\
 	&Pr(T)=P(C)=P(G) \\
        & = \dfrac{1}{300} \\ 
        &= 0.003333333
\end{align}
likelihood ratio: 
\begin{align}
	 	& = \frac{P(Data\|Hete)}{P(Data\|Homo)}  \\
 		& = \frac{(0.4966667^{10} * 0.4966667^{4} * 0.003333333}{0.99^{10} * ({0.003333333}^{4} * 0.003333333} \\
    	% & = \frac{\Sexpr{0.4966667^10 * 0.4966667^4 * 0.003333333}}{\Sexpr{0.9801333^10 *  0.006622223^5}} \\
    & = \frac{1.852633e-07}{3.721735e-13} \\
 		& = 497787.5
 \end{align}
\textbf{2.b.Sol:}

For: $P_{homo}(P\|data)$
\begin{align}
		P(AC) &=  1.8526 * 10{-7}  \\
		% &= \Sexpr{ 1.8526 * 10e-7} \\
		P(AA) &=  3.721735e-13 \\
		P(CC) &= 0.99^{4} * 0.003333333^{10} * 0.003333333  \\
		% & = $\Sexpr{0.99^4 * 0.01^10 * 0.01}$ \\
		& =  5.422587e-28
\end{align}
$P_{hete}(P\|data)$
\begin{align}
		&=\frac{P_{hete}(data\|P) * P_{hete}(P)}{\sum_{i=1}^{3}P(data\|P_{i})} \\
		% &= \frac{((^{15}_{10})*P * 81\%}{(^{15}_{10}P * 0.81 + (^{15}_{14})*P*0.18 + (^{15}_{0})*P*0.01 } \\
% 		% &= \dfrac{\Sexpr{choose(15,10) * choose(15,4)*1.8526 * 10e-7 * 0.81}}{\Sexpr{0.00450632 + 0.1037932 * 0.18 + 7.197877e-13 * 0.01 }}\\
		&= \frac{1.8526 * 10e-7 * 0.81}{(1.8526 * 10e-7 * 0.81 + 3.721735 * 10e-13 * 0.18 + 5.422587*10e-28 * 0.01)} \\
		% &= $\Sexpr{1.500606e-06/(1.500606e-06 + 6.699123e-13)}$ \\
		&=0.9999993
\end{align}
$P_{homo}(P\|data)$
\begin{align}
		&=\frac{P_{homo}(data\|P) * P_{homo}(P)}{\sum_{i=1}^{3}P(data\|P_{i})} \\
		&= \frac{3.721735 * 10e-13 * 0.18 }{(1.8526 * 10e-7 * 0.81 + 3.721735e-13 * 0.18 + 1.755967e-19 * 0.01)} \\
		&= \dfrac{1.500606e-06}{1.500607e-06} \\
% 		&= \Sexpr{1.500606e-06/1.500607e-06} 
		&=7e-07
\end{align}

\textbf{2.c.Sol:} Noted that, 

\begin{align}
	P(\text{novel heterozygote}) & = \frac{300,000}{3*10^9-3*10^7} \\ 
		& = 0.0001010101 \\
	% P(\text{non-reference allele heterozygote}) & = \frac{3 * 10^{7}}{3*10^9-3*10^7} \\
		% & = 0.01010101\\
	P(\text{homo}) & = 1- 0.0001010101 \\
		% & = $\Sexpr{1- 0.0001010101}$ 
		& = 0.999899
\end{align}
$P(data|Hete)$
\begin{align}
	&= \frac{P(Hete|data)*P(Hete)}{P(data)} \\
	&= \frac{1.8526 * 10e-7 * 0.0001010101 }{(1.8526 * 10e-7 * 0.0001010101+ 3.721735e-13 * 0.999899)} \\  
	% &=\Sexpr{1.8526 * 10e-7 * 0.0001010101/(1.8526 * 10e-7 * 0.0001010101+ 3.721735e-13 * 0.999899)} \\
	&= \frac{1.871313e-10}{ 1.875034e-10} \\
	&= 0.9980155
\end{align}
 $P(data|Homo)$
\begin{align} 
	&= \frac{P(Homo|data)*P(Homo)}{P(data)} \\
	&= \frac{3.721735e-13 * 0.999899}{(1.8526 * 10e-7 * 0.0001010101+ 3.721735e-13 * 0.999899)} \\  
	&= \frac{3.721359e-13}{1.875034e-10} \\
	&= 0.001984688
\end{align}
\textbf{2.d.Sol:} 

for heterozygote, per 2.a 
\begin{align}
& P(non-reference allel) = \frac{1}{300}
& P(A) = 0.99
\end{align}
Using Possion model for the read number, \lambda = x/300, \\
X \sim \operatorname{Pois}\left({\lambda}\right)

for interval [11,a], the prob of calling a false positive when observing x reads is : \\
when i = [11,a], 
\begin{align}
P( x \geq 4) & = \sum_{i=11}^{i=a}{Pois}\left({\lambda}\right) \\
\end{align}
when i = [a+1,b], 
\begin{align}
P(b \geq x \geq (a+1)) & = \sum_{i=(a+1)}^{i=b}{Pois}\left({\lambda}\right) \\
\end{align}
when i = [b+1,29], 
\begin{align}
P(29 \geq x \geq (b+1)) & = \sum_{i=(b+1)}^{i=29}{Pois}\left({\lambda}\right) \\
\end{align}  

<<2.d>>=
 
 mybinom <- function(x,i) {
 	p <- 0.01
 	return(sum(choose(i,x)*(p)^x*(1-p)^(i-x)))
 }
 for(a in 11:28)
 { res<-0;  x<-c(0:3)
   for(i in 11:a)
   {res<-res+1-mybinom(x,i) }
   for(b in (a+1):28)
   {  x<-c(0:4)
      for(i in (a+1):b)
	    {res<-res+1-mybinom(x,i)}
      for(c in (b+1):29)
      { x<-c(0:5)
        res<-res+1-mybinom(x,i)
      }
      if(res>0.01) {print(c(as.character(a),as.character(b),res)) }
   }
 }
@
So, basically, we can choose random a, b in [11,29]

\textbf{2.e.Sol:}

For a possion with $\lambda = 20$, 
$P(30>X>10) \sim \operatorname{Pois} \left({\lambda}\right)$
<<2.e.1>>=
ppois(29,20,lower.tail=T)-ppois(9,20,lower.tail=T)
@
#0.9731864 #0.0268136 ignore
\textbf{2.f.Sol:}

For possion distribution, \lambda = 20, when a =15, b=19 \\
\begin{align}
	&P_1= \sum_11^{15}\dpois(i,20) * P(call Hete)
    &P_1= \sum_16^{19}\dpois(i,20) * P(call Hete)
	&P_1= \sum_{20}^{19}\dpois(i,20) * P(call Hete)
\end{align}

<<2.e.2>>=
p_hete<-function(i,cutoff)
	{ 1-ppois(cutoff-1,i*0.4966667)}
p_1 <- sum(unlist(lapply(11:15,FUN=function(x){dpois(x,20) * p_hete(x,4) })))
p_2 <- sum(unlist(lapply(16:19,FUN=function(x){dpois(x,20) * p_hete(x,4) })))
p_3 <- sum(unlist(lapply(20:29,FUN=function(x){dpois(x,20) * p_hete(x,4) })))
p_1 + p_2 + p_3
@

\textbf{2.g.Sol:}

Heterozygote AC:
\begin{align}
	& P(data|hete) \\
	&= (1-10^{-3.7})*(1-10^{-3.3})*(1-10^{-3.0}) \\
	& *(1-10^{-2.7})*(1-10^{-2.3})*(1-10^{-2.0}) \\
	& *(1-10^{-1.7})*(1-10^{-1.3})*(1-10^{-1.0}) \\ 
	& *(1-10^{-0.7})* (1-10^{-1.7}) *(1-10^{-1.3}) \\
	& * (1-10^{-1.0}) * (1- 10^{-0.7}) * 10^{-0.3} \\ 
	% =\Sexpr{(1-10^(-3.7))*(1-10^(-3.3))*(1-10^(-3.0))*(1-10^(-2.7))*(1-10^(-2.3))*(1-10^(-2.0))*(1-10^(-1.7))*(1-10^(-1.3))*(1-10^(-1.0))*(1-10^(-0.7))* (1-10^(-1.7)) *(1-10^(-1.3))* (1-10^(-1.0)) *  (1- 10^(-0.7)) * 10^(-0.3) } \\ 
	&= 0.2212375
\end{align}

Homozygote AA: 

\begin{align}
	& P(data|Homo) \\
	&= (1-10^{-3.7})*(1-10^{-3.3})*(1-10^{-3.0}) \\
	& *(1-10^{-2.7})*(1-10^{-2.3})*(1-10^{-2.0}) \\
	& *(1-10^{-1.7})*(1-10^{-1.3})*(1-10^{-1.0}) \\ 
	& *(1-10^{-0.7})* 10^{-1.7} *10^{-1.3} \\
	& * 10^{-1.0} * 10^{-0.7} * 10^{-0.3} \\  
	% =\Sexpr{(1-10^(-3.7))*(1-10^(-3.3))*(1-10^(-3.0))*(1-10^(-2.7))*(1-10^(-2.3))*(1-10^(-2.0))*(1-10^(-1.7))*(1-10^(-1.3))*(1-10^(-1.0))*(1-10^(-0.7))* 10^(-1.7) *10^(-1.3)*10^(-1.0) * 10^(-0.7) * 10^(-0.3) } \\ 
	&= 6.581923e-06
 
\end{align}
likelihood ratio: 
\begin{align}
	 	& = \frac{P(Data\|Hete)}{P(Data\|Homo)}  \\
 		& = \frac{0.2212375}{6.581923e-06} \\
 		% & =\Sexpr{0.2212375/6.581923e-06}
 		& = 33612.9
\end{align}

\textbf{3.a.Sol:}
The average distance between two reads $1000-2 * 100 = 800$ bp, with the $std = 200$ bp. 

\begin{align}
& Z =\frac{(x-u)}{std/\sqrt{n}} = \frac{(1250-800)}{200/\sqrt{n}} \\
& P( Z < z_{\alpha}) = 1- \alpha\\
& p^{n} < 10e-6 \\
& nlog(p) < log(10e-6)
\end{align}
<<3.a>>=
n <- 0
repeat{
   n <- n + 1
	 z <- (1250-800)/(200/sqrt(n))
   p <- 1 - pnorm(z)
   if( p <10^(-6))
     {print(p)
      print(n)
      break
      }
}
@

n= 5 \\
% &= \int_\infty^x\frac{1}{{\sigma \sqrt {2\pi } }}e^{{{ - \left( {x - \mu } \right)^2 } \mathord{\left/ {\vphantom {{ - \left( {x - \mu } \right)^2 } {2\sigma ^2 }}} \right. \kern-\nulldelimiterspace} {2\sigma ^2 }}} \\
\textbf{3.b.Sol:} 

according to Possion distrition, with $\lambda=5$ 

\begin{align}
& p(x) = \frac{\lambda^{x}exp{(-\lambda)}}{x\!} \\
& p(x < 5) = \sum_{i=0}^{4}\frac{5^{x}exp{-5}}{5\!} \\
& = 0.4404933
\end{align}

Disclosure: Discuss with kuixi zhu, Boris, Ola, & nanfang,xu

\end{document}




